--3.
DROP TYPE ListaPeldanos;
DROP TYPE MODELO;
DROP TYPE PELDANO; 
CREATE OR REPLACE TYPE PELDANO AS OBJECT(
    ANCHO NUMBER (10,2),
    ALTO NUMBER (10,2),
    FONDO NUMBER (0, 2)
) NOT FINAL;

CREATE OR REPLACE TYPE MODELO UNDER PELDANO (
    CODIGO CHAR(1),
    DESCMODELO VARCHAR2(10),
    MAP MEMBER FUNCTION ORDENAR RETURN CHAR 
);

CREATE OR REPLACE TYPE BODY MODELO AS
    MAP MEMBER FUNCTION ORDENAR RETURN CHAR
    IS
    BEGIN 
     RETURN CODIGO;
    END;
END;
/

CREATE OR REPLACE TYPE ListaPeldanos AS TABLE OF PELDANO;
/