-- LOCALIDADES TOMA UNICAMENTE EL ID DEL TABLA MUNCIPIO
SELECT * FROM LOCALIDADES;
SELECT * FROM LOCALIDADES WHERE NOMBRE_LOC = 'Limpias';
SELECT * FROM LOCALIDADES WHERE MUNICIPIO = 38;
SELECT * FROM MUNICIPIOS;
SELECT id, NOMBRE FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('Limpias');

--BUSCAMOS EL ID EN LA TABLA DE MUNICIPIOS PARA LOCALIZAR LIMPIAS
DELETE (SELECT * FROM LOCALIDADES WHERE MUNICIPIO = 38);
INSERT INTO LOCALIDADES (MUNICIPIO, NUMERO, NOMBRE_LOC, HABITANTES) 
VALUES ((SELECT id FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('Limpias')), 1, 'Limpias', 1329);

INSERT INTO LOCALIDADES (MUNICIPIO, NUMERO, NOMBRE_LOC, HABITANTES) 
VALUES ((SELECT id FROM MUNICIPIOS WHERE NOMBRE = 'Limpias'), 2, 'Seña', 347);

-- B
ALTER TRIGGER PERSONAS_IDPERS_TRIG DISABLE;

SELECT * FROM PERSONAS;
DELETE (SELECT * FROM PERSONAS WHERE IDPERS BETWEEN 943 AND 946);

INSERT INTO PERSONAS(IDPERS, NOMBRE, APELLIDOS) VALUES (943,'AMARA', 'CASTILLO MARTÍNEZ');
INSERT INTO PERSONAS(IDPERS, NOMBRE, APELLIDOS) VALUES (944,'LUIS', 'RUIZ GARCIA');
INSERT INTO PERSONAS(IDPERS, NOMBRE, APELLIDOS) VALUES (945,'ANTONIO', 'RAMIREZ RAMIREZ');
INSERT INTO PERSONAS(IDPERS, NOMBRE, APELLIDOS) VALUES (946,'JOSE', 'SAINZ SAINZ');

ALTER TRIGGER PERSONAS_IDPERS_TRIG ENABLE;


-- HAGAMOS AHORA UN BLOQUE

DECLARE
   ID_MUNICIPIO INTEGER;
    BEGIN
        SELECT ID INTO ID_MUNICIPIO
        FROM MUNICIPIOS 
        WHERE LOWER(NOMBRE) = LOWER ('Arredondo');
        
        INSERT INTO CONCEJALES (IDPERS, PARTIDO, MUNICIPIO) VALUES(943, 'PRC', ID_MUNICIPIO);
        INSERT INTO CONCEJALES (IDPERS, PARTIDO, MUNICIPIO) VALUES(944, 'PRC', ID_MUNICIPIO);
        INSERT INTO CONCEJALES (IDPERS, PARTIDO, MUNICIPIO) VALUES(945, 'PRC', ID_MUNICIPIO);
        INSERT INTO CONCEJALES (IDPERS, PARTIDO, MUNICIPIO) VALUES(946, 'PRC', ID_MUNICIPIO);
    END;
/

SELECT * FROM CONCEJALES; 
DELETE (SELECT IDPERS FROM CONCEJALES WHERE IDPERS BETWEEN 943 AND 946);


-- C. MODIFICAR

SELECT ID FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('ALFOZ DE LLOREDO');

SELECT * FROM LOCALIDADES WHERE MUNICIPIO = (SELECT ID FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('ALFOZ DE LLOREDO')) AND HABITANTES > 200;

UPDATE LOCALIDADES
SET HABITANTES = HABITANTES *1.02
WHERE MUNICIPIO = (SELECT ID FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('ALFOZ DE LLOREDO')) 
AND HABITANTES > 200;

SELECT * FROM LOCALIDADES WHERE MUNICIPIO = (SELECT ID FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('ALFOZ DE LLOREDO')) AND HABITANTES > 200;

ROLLBACK;

--D. ELIMINA LA LOCALIDAD CARBROJO
SELECT * FROM LOCALIDADES WHERE LOWER(NOMBRE_LOC)= LOWER('CABROJO');
SELECT * FROM MUNICIPIOS WHERE LOWER(NOMBRE) = LOWER('CABEZÓN DE LA SAL');

DELETE FROM LOCALIDADES 
WHERE LOWER(NOMBRE_LOC)= LOWER('CABROJO') 
AND MUNICIPIO = (
    SELECT ID FROM MUNICIPIOS 
    WHERE LOWER(NOMBRE) = LOWER('CABEZÓN DE LA SAL')
    );
    
SELECT * FROM LOCALIDADES WHERE LOWER(NOMBRE_LOC)= LOWER('CABROJO') ;
ROLLBACK; 
