/**INSERTANDO REGISTROS EN LA TABLA PROFESORADO**/

INSERT INTO PROFESORADO(CODIGO, NOMBRE, APELLIDOS, DNI, ESPECIALIDAD, FECHA_NAC, ANTIGUEDAD) VALUES ('2', 'MARIA LUISA', 'FABRE BERDUN', '51083099F', 'TECNOLOGIA','31/03/1975', '4');
INSERT INTO PROFESORADO(CODIGO, NOMBRE, APELLIDOS, ESPECIALIDAD, FECHA_NAC, ANTIGUEDAD) VALUES ('3', 'JAVIER', 'JIMENEZ HERNANDO', 'LENGUA','04/05/1969', '10');
INSERT INTO PROFESORADO(CODIGO, NOMBRE, APELLIDOS, DNI, ESPECIALIDAD, FECHA_NAC, ANTIGUEDAD) VALUES ('4', 'ESTEFANIA', 'FERNANDEZ MARTINEZ', '19964324W', 'INGLES','22/06/1973', '5');
INSERT INTO PROFESORADO(CODIGO, NOMBRE, APELLIDOS) VALUES('5', 'JOSE M.', 'ANERO PAYAN');

/**MODIFICANDO REGISTROS DE LA TABLA PROFESORADO AL PROFESOR CON CODIGO 3**/
UPDATE PROFESORADO SET ESPECIALIDAD = 'INFORMATICA', DNI = '9876543C' WHERE CODIGO ='3';

/**MODIFICANDO LAS ANTIGÜEDADES DE TODOS LOS PROFESORES E INCREMENTANDOLAS EN 2 EN LOS LOS REGISTROS DONDE LA ANTIGUEDAD SEA SUPERIOR A 2**/
UPDATE PROFESORADO SET ANTIGUEDAD = ANTIGUEDAD + 2 WHERE ANTIGUEDAD > 2;

/** ELIMINAR DE LA TABLA ALUMNADO LOS REGISTROS ASOCIADOS A COD_CURSO=2 Y SEXO = H**/
DELETE FROM ALUMNADO WHERE SEXO = 'H' AND COD_CURSO ='2';


/**INSERTAR LOS REGISTROS DE LA TABLA ALUMNADO_NUEVO EN LA TABLA ALUMNADO**/
INSERT INTO ALUMNADO(NOMBRE, APELLIDOS, SEXO, FECHA_NAC) SELECT NOMBRE, APELLIDOS, SEXO, FECHA_NAC FROM ALUMNADO_NUEVO;

/** ACTULIZANDO EL CAMPO MAX_ALUMN DEL REGISTRO DEL CURSO CON CODIGO 1 ASIGNANDOLE EL VALOR CORRESPONDIENTE AL NUMERO TOTAL
DE ALUMNOS QUE HAY EN LA TABLA ALUMNADO, PARA ELLO CONTAMOS LOS ALUMNOS DE LA TABLA ALUMNADO CON ESE CODIGO DE CURSO **/
UPDATE CURSOS SET MAX_ALUMN = (SELECT COUNT(*) FROM ALUMNADO WHERE COD_CURSO='1') WHERE CODIGO='1';

/**ELIMINANDO DE LA TABLA ALUMNADO TODOS LOS REGISTROS A LOS CURSOS DEL PROFESOR CON EL CODIGO '3'; PRIMERO BUSCAMOS EL CODIGO DEL PROFESOR
Y EN TABLA CURSOS BUSCAMOS LOS CURSOS QUE IMPARTE**/
DELETE FROM ALUMNADO WHERE COD_CURSO =(SELECT CODIGO FROM CURSOS WHERE COD_PROFE =(SELECT CODIGO FROM PROFESORADO WHERE CODIGO='3'));

/**ELIMINANDO DE LA TABLA ALUMNADO TODOS LOS REGISTROS A LOS CURSOS DEL PROFESOR CON EL CODIGO '2'; PRIMERO BUSCAMOS EL CODIGO DEL PROFESOR
Y EN TABLA CURSOS BUSCAMOS LOS CURSOS QUE IMPARTE**/
DELETE FROM ALUMNADO WHERE COD_CURSO IN (SELECT CODIGO FROM CURSOS WHERE COD_PROFE =(SELECT CODIGO FROM PROFESORADO WHERE CODIGO='2'));
